version: '3'
name: 'leal-challenge'
services:
  lc-database:
    build:
      context: ./internal/db/postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "leal-challenge-database", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 5
    networks:
      - leal-challenge-network

  smb-rest:
    build:
      context: ./
    environment:
      - POSTGRES_HOST=lc-database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=leal-challenge-database
      - GIN_MODE=release
    ports:
      - '8010:8010'
    depends_on:
      lc-database:
        condition: service_healthy
    networks:
      - leal-challenge-network
networks:
  leal-challenge-network: